[metadata]
name = PyCTP
version = 2.1.0
description = Python bindings for CTP
long_description = file: README.md
long_description_content_type = text/markdown
author = Shi Zhuolin
author_email = shizhuolin@hotmail.com
license = LGPL-3.0
keywords =
    ctp
    pyctp
    futures
    stock
url = https://github.com/shizhuolin/PyCTP
platforms =
    linux-x86_64
    win32
    win-amd64

[options]
python_requires = >=3.6
zip_safe = False
include_package_data = True
package_dir =
    = pkg
packages = find:

[options.packages.find]
where = pkg

[options.package_data]
PyCTP =
    libs/*.so
    libs/*.dll