//数据结构与pydict互转


#ifndef PYCTP_USERAPISTRUCT_H
#define PYCTP_USERAPISTRUCT_H

#include <ThostFtdcUserApiStruct.h>

PyObject *PyCTP_PyDict_FromStruct(CThostFtdcExchangeField *pExchangeField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcQryStrikeOffsetField *pQryStrikeOffsetField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcExchangeExecOrderActionField *pExchangeExecOrderActionField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcQryBrokerUserFunctionField *pQryBrokerUserFunctionField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcTraderOfferField *pTraderOfferField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcCommRateModelField *pCommRateModelField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcQryCommRateModelField *pQryCommRateModelField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcInvestorPositionDetailField *pInvestorPositionDetailField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcQryCombActionField *pQryCombActionField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcQrySyncStatusField *pQrySyncStatusField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcInstrumentTradingRightField *pInstrumentTradingRightField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcExchangeOrderActionErrorField *pExchangeOrderActionErrorField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcQryDepthMarketDataField *pQryDepthMarketDataField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcUserIPField *pUserIPField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcProductExchRateField *pProductExchRateField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcQryInvestorGroupField *pQryInvestorGroupField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcQryProductGroupField *pQryProductGroupField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcVerifyInvestorPasswordField *pVerifyInvestorPasswordField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcCFMMCTradingAccountKeyField *pCFMMCTradingAccountKeyField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcRspRepealField *pRspRepealField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcQryInstrumentField *pQryInstrumentField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcInputQuoteField *pInputQuoteField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcReqCancelAccountField *pReqCancelAccountField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcBrokerUserField *pBrokerUserField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcQryTradeField *pQryTradeField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcQryUserSessionField *pQryUserSessionField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcMarketDataAveragePriceField *pMarketDataAveragePriceField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcRspTransferField *pRspTransferField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcQryTradingNoticeField *pQryTradingNoticeField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcSettlementInfoConfirmField *pSettlementInfoConfirmField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcQryLoginForbiddenUserField *pQryLoginForbiddenUserField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcQryQuoteField *pQryQuoteField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcReqAuthenticateField *pReqAuthenticateField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcSyncingInvestorPositionField *pSyncingInvestorPositionField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcAccountregisterField *pAccountregisterField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcQryBrokerField *pQryBrokerField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcMDTraderOfferField *pMDTraderOfferField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcBrokerWithdrawAlgorithmField *pBrokerWithdrawAlgorithmField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcBrokerDepositField *pBrokerDepositField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcQryInvestorProductGroupMarginField *pQryInvestorProductGroupMarginField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcQryQuoteActionField *pQryQuoteActionField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcQryProductField *pQryProductField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcQryExecOrderField *pQryExecOrderField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcBatchOrderActionField *pBatchOrderActionField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcMarketDataStaticField *pMarketDataStaticField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcLoadSettlementInfoField *pLoadSettlementInfoField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcInputQuoteActionField *pInputQuoteActionField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcQryBrokerUserField *pQryBrokerUserField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcQryExchangeSequenceField *pQryExchangeSequenceField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcMarketDataAsk45Field *pMarketDataAsk45Field);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcVerifyFuturePasswordField *pVerifyFuturePasswordField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcReturnResultField *pReturnResultField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcSettlementInfoField *pSettlementInfoField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcTradingAccountPasswordUpdateV1Field *pTradingAccountPasswordUpdateV1Field);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcSyncDepositField *pSyncDepositField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcProductField *pProductField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcQryExchangeMarginRateField *pQryExchangeMarginRateField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcCombActionField *pCombActionField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcInputExecOrderField *pInputExecOrderField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcRspAuthenticateField *pRspAuthenticateField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcExchangeRateField *pExchangeRateField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcRspUserLoginField *pRspUserLoginField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcQryExchangeQuoteField *pQryExchangeQuoteField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcQryExchangeMarginRateAdjustField *pQryExchangeMarginRateAdjustField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcQryTransferBankField *pQryTransferBankField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcQryBrokerTradingParamsField *pQryBrokerTradingParamsField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcQryExchangeExecOrderActionField *pQryExchangeExecOrderActionField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcPositionProfitAlgorithmField *pPositionProfitAlgorithmField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcReqRepealField *pReqRepealField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcQueryMaxOrderVolumeField *pQueryMaxOrderVolumeField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcQryInvestorPositionCombineDetailField *pQryInvestorPositionCombineDetailField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcSyncingInvestorGroupField *pSyncingInvestorGroupField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcExchangeQuoteActionField *pExchangeQuoteActionField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcInputOrderField *pInputOrderField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcErrorConditionalOrderField *pErrorConditionalOrderField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcOptionInstrMarginAdjustField *pOptionInstrMarginAdjustField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcQueryBrokerDepositField *pQueryBrokerDepositField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcUserLogoutField *pUserLogoutField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcQrySettlementInfoConfirmField *pQrySettlementInfoConfirmField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcTransferSerialField *pTransferSerialField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcMarketDataExchangeField *pMarketDataExchangeField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcTradingAccountField *pTradingAccountField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcQryOptionInstrCommRateField *pQryOptionInstrCommRateField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcInstrumentField *pInstrumentField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcContractBankField *pContractBankField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcSpecificInstrumentField *pSpecificInstrumentField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcPartBrokerField *pPartBrokerField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcMarketDataField *pMarketDataField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcQryCFMMCBrokerKeyField *pQryCFMMCBrokerKeyField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcQryNoticeField *pQryNoticeField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcExchangeTradeField *pExchangeTradeField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcQuoteField *pQuoteField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcTradingAccountPasswordUpdateField *pTradingAccountPasswordUpdateField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcTradingNoticeInfoField *pTradingNoticeInfoField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcQryExchangeRateField *pQryExchangeRateField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcNotifyFutureSignInField *pNotifyFutureSignInField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcRspInfoField *pRspInfoField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcAuthenticationInfoField *pAuthenticationInfoField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcDepositResultInformField *pDepositResultInformField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcCFMMCTradingAccountTokenField *pCFMMCTradingAccountTokenField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcMulticastGroupInfoField *pMulticastGroupInfoField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcUserSessionField *pUserSessionField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcUserRightField *pUserRightField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcQryExchangeField *pQryExchangeField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcRspQueryTradeResultBySerialField *pRspQueryTradeResultBySerialField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcRspQueryAccountField *pRspQueryAccountField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcCurrentTimeField *pCurrentTimeField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcParkedOrderActionField *pParkedOrderActionField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcExchangeOrderActionField *pExchangeOrderActionField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcOptionInstrCommRateField *pOptionInstrCommRateField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcReqSyncKeyField *pReqSyncKeyField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcSyncingInstrumentTradingRightField *pSyncingInstrumentTradingRightField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcProductGroupField *pProductGroupField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcQueryMaxOrderVolumeWithPriceField *pQueryMaxOrderVolumeWithPriceField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcCombInstrumentGuardField *pCombInstrumentGuardField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcForQuoteField *pForQuoteField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcErrExecOrderActionField *pErrExecOrderActionField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcSyncStatusField *pSyncStatusField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcQrySyncFundMortgageField *pQrySyncFundMortgageField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcMarketDataBid23Field *pMarketDataBid23Field);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcExchangeOrderInsertErrorField *pExchangeOrderInsertErrorField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcMarketDataBid45Field *pMarketDataBid45Field);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcQryForQuoteField *pQryForQuoteField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcQryForQuoteParamField *pQryForQuoteParamField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcMarketDataBaseField *pMarketDataBaseField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcErrExecOrderField *pErrExecOrderField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcStrikeOffsetField *pStrikeOffsetField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcLoginInfoField *pLoginInfoField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcQryPartBrokerField *pQryPartBrokerField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcInputOrderActionField *pInputOrderActionField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcQuoteActionField *pQuoteActionField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcQryExchangeForQuoteField *pQryExchangeForQuoteField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcParkedOrderField *pParkedOrderField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcOptionInstrDeltaField *pOptionInstrDeltaField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcInstrumentMarginRateAdjustField *pInstrumentMarginRateAdjustField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcQryParkedOrderField *pQryParkedOrderField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcExecOrderField *pExecOrderField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcNotifyFutureSignOutField *pNotifyFutureSignOutField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcNoticeField *pNoticeField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcRspSyncKeyField *pRspSyncKeyField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcTransferBankToFutureReqField *pTransferBankToFutureReqField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcForQuoteParamField *pForQuoteParamField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcQryInstrumentTradingRightField *pQryInstrumentTradingRightField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcMarketDataAsk23Field *pMarketDataAsk23Field);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcDiscountField *pDiscountField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcQryExchangeOrderActionField *pQryExchangeOrderActionField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcReqFutureSignOutField *pReqFutureSignOutField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcQryErrExecOrderActionField *pQryErrExecOrderActionField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcReqTransferField *pReqTransferField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcExchangeForQuoteField *pExchangeForQuoteField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcRspFutureSignOutField *pRspFutureSignOutField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcReqOpenAccountField *pReqOpenAccountField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcBrokerUserFunctionField *pBrokerUserFunctionField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcQryOptionInstrTradingRightField *pQryOptionInstrTradingRightField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcQryParkedOrderActionField *pQryParkedOrderActionField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcInputCombActionField *pInputCombActionField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcQryBrokerUserEventField *pQryBrokerUserEventField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcTransferQryBankRspField *pTransferQryBankRspField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcMarketDataLastMatchField *pMarketDataLastMatchField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcInputBatchOrderActionField *pInputBatchOrderActionField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcInvestorPositionField *pInvestorPositionField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcExchangeMarginRateField *pExchangeMarginRateField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcQryBrokerTradingAlgosField *pQryBrokerTradingAlgosField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcTransferQryBankReqField *pTransferQryBankReqField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcOrderActionField *pOrderActionField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcQrySuperUserFunctionField *pQrySuperUserFunctionField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcErrOrderField *pErrOrderField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcDRTransferField *pDRTransferField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcRemoveParkedOrderActionField *pRemoveParkedOrderActionField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcInvestorProductGroupMarginField *pInvestorProductGroupMarginField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcFutureSignIOField *pFutureSignIOField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcQryErrOrderActionField *pQryErrOrderActionField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcQryInstrumentCommissionRateField *pQryInstrumentCommissionRateField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcInstrumentCommissionRateField *pInstrumentCommissionRateField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcTransferQryDetailReqField *pTransferQryDetailReqField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcBrokerUserPasswordField *pBrokerUserPasswordField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcQryExchangeExecOrderField *pQryExchangeExecOrderField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcQryBatchOrderActionField *pQryBatchOrderActionField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcEWarrantOffsetField *pEWarrantOffsetField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcFrontStatusField *pFrontStatusField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcDepthMarketDataField *pDepthMarketDataField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcMarketDataBestPriceField *pMarketDataBestPriceField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcCombinationLegField *pCombinationLegField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcInvestorPositionCombineDetailField *pInvestorPositionCombineDetailField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcOptionInstrTradeCostField *pOptionInstrTradeCostField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcMarginModelField *pMarginModelField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcFensUserInfoField *pFensUserInfoField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcExchangeCombActionField *pExchangeCombActionField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcTradingAccountReserveField *pTradingAccountReserveField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcQrySyncDepositField *pQrySyncDepositField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcQrySecAgentACIDMapField *pQrySecAgentACIDMapField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcInstrumentMarginRateField *pInstrumentMarginRateField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcBrokerTradingAlgosField *pBrokerTradingAlgosField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcRspFutureSignInField *pRspFutureSignInField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcQryExchangeCombActionField *pQryExchangeCombActionField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcCFMMCBrokerKeyField *pCFMMCBrokerKeyField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcExchangeMarginRateAdjustField *pExchangeMarginRateAdjustField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcQryTradingAccountField *pQryTradingAccountField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcQrySuperUserField *pQrySuperUserField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcSecAgentACIDMapField *pSecAgentACIDMapField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcReqQueryAccountField *pReqQueryAccountField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcQryMarginModelField *pQryMarginModelField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcTransferQryDetailRspField *pTransferQryDetailRspField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcQryProductExchRateField *pQryProductExchRateField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcInvestorField *pInvestorField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcDisseminationField *pDisseminationField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcReqChangeAccountField *pReqChangeAccountField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcQryOrderActionField *pQryOrderActionField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcInputForQuoteField *pInputForQuoteField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcTransferBankField *pTransferBankField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcQryInvestorPositionField *pQryInvestorPositionField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcTraderField *pTraderField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcQryInstrumentStatusField *pQryInstrumentStatusField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcTransferHeaderField *pTransferHeaderField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcTradeField *pTradeField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcSyncingTradingAccountField *pSyncingTradingAccountField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcUserRightsAssignField *pUserRightsAssignField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcCancelAccountField *pCancelAccountField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcBrokerField *pBrokerField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcQryExchangeOrderField *pQryExchangeOrderField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcReqUserLoginField *pReqUserLoginField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcBrokerSyncField *pBrokerSyncField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcCurrTransferIdentityField *pCurrTransferIdentityField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcTransferFutureToBankRspField *pTransferFutureToBankRspField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcBrokerUserEventField *pBrokerUserEventField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcQryExchangeQuoteActionField *pQryExchangeQuoteActionField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcOptionInstrTradingRightField *pOptionInstrTradingRightField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcInvestorGroupField *pInvestorGroupField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcReqDayEndFileReadyField *pReqDayEndFileReadyField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcLogoutAllField *pLogoutAllField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcNotifyQueryAccountField *pNotifyQueryAccountField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcSuperUserFunctionField *pSuperUserFunctionField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcBrokerTradingParamsField *pBrokerTradingParamsField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcOpenAccountField *pOpenAccountField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcSyncFundMortgageField *pSyncFundMortgageField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcInstrumentStatusField *pInstrumentStatusField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcQryContractBankField *pQryContractBankField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcTradingCodeField *pTradingCodeField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcQryInvestorField *pQryInvestorField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcTradingNoticeField *pTradingNoticeField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcRemoveParkedOrderField *pRemoveParkedOrderField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcOrderField *pOrderField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcMarketDataUpdateTimeField *pMarketDataUpdateTimeField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcVerifyCustInfoField *pVerifyCustInfoField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcQryErrOrderField *pQryErrOrderField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcUserPasswordUpdateField *pUserPasswordUpdateField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcQryTransferSerialField *pQryTransferSerialField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcNotifySyncKeyField *pNotifySyncKeyField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcSuperUserField *pSuperUserField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcExchangeOrderField *pExchangeOrderField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcQryTraderField *pQryTraderField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcIndexPriceField *pIndexPriceField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcQryExecOrderActionField *pQryExecOrderActionField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcQryErrExecOrderField *pQryErrExecOrderField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcErrOrderActionField *pErrOrderActionField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcSyncingTradingCodeField *pSyncingTradingCodeField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcSyncingInstrumentCommissionRateField *pSyncingInstrumentCommissionRateField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcInvestorAccountField *pInvestorAccountField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcLoginForbiddenUserField *pLoginForbiddenUserField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcInputExecOrderActionField *pInputExecOrderActionField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcLinkManField *pLinkManField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcVerifyFuturePasswordAndCustInfoField *pVerifyFuturePasswordAndCustInfoField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcQryLinkManField *pQryLinkManField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcQryInvestorPositionDetailField *pQryInvestorPositionDetailField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcExecOrderActionField *pExecOrderActionField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcQryHisOrderField *pQryHisOrderField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcOptionInstrMiniMarginField *pOptionInstrMiniMarginField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcTransferBankToFutureRspField *pTransferBankToFutureRspField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcExchangeQuoteField *pExchangeQuoteField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcQrySettlementInfoField *pQrySettlementInfoField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcQryOptionInstrTradeCostField *pQryOptionInstrTradeCostField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcExchangeBatchOrderActionField *pExchangeBatchOrderActionField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcExchangeSequenceField *pExchangeSequenceField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcQryOrderField *pQryOrderField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcQryEWarrantOffsetField *pQryEWarrantOffsetField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcQueryCFMMCTradingAccountTokenField *pQueryCFMMCTradingAccountTokenField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcBrokerUserOTPParamField *pBrokerUserOTPParamField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcInvestorWithdrawAlgorithmField *pInvestorWithdrawAlgorithmField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcQryAccountregisterField *pQryAccountregisterField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcQryCFMMCTradingAccountKeyField *pQryCFMMCTradingAccountKeyField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcChangeAccountField *pChangeAccountField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcQryTraderOfferField *pQryTraderOfferField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcBrokerUserRightAssignField *pBrokerUserRightAssignField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcForQuoteRspField *pForQuoteRspField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcExchangeExecOrderField *pExchangeExecOrderField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcCommPhaseField *pCommPhaseField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcQryTradingCodeField *pQryTradingCodeField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcForceUserLogoutField *pForceUserLogoutField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcSettlementRefField *pSettlementRefField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcQryCombInstrumentGuardField *pQryCombInstrumentGuardField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcSyncingInstrumentMarginRateField *pSyncingInstrumentMarginRateField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcQryInstrumentMarginRateField *pQryInstrumentMarginRateField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcReqQueryTradeResultBySerialField *pReqQueryTradeResultBySerialField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcSyncingInvestorField *pSyncingInvestorField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcQryFrontStatusField *pQryFrontStatusField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcQryMDTraderOfferField *pQryMDTraderOfferField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcQryCombinationLegField *pQryCombinationLegField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcTradingAccountPasswordField *pTradingAccountPasswordField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcTransferFutureToBankReqField *pTransferFutureToBankReqField);
PyObject *PyCTP_PyDict_FromStruct(CThostFtdcManualSyncBrokerUserOTPField *pManualSyncBrokerUserOTPField);

int PyCTP_Struct_FromPyDict(CThostFtdcQryErrOrderActionField *pQryErrOrderActionField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcQryCFMMCBrokerKeyField *pQryCFMMCBrokerKeyField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcErrorConditionalOrderField *pErrorConditionalOrderField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcTransferBankToFutureReqField *pTransferBankToFutureReqField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcCurrTransferIdentityField *pCurrTransferIdentityField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcDRTransferField *pDRTransferField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcQueryCFMMCTradingAccountTokenField *pQueryCFMMCTradingAccountTokenField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcUserRightField *pUserRightField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcQryInvestorPositionField *pQryInvestorPositionField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcTransferQryDetailRspField *pTransferQryDetailRspField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcQryQuoteField *pQryQuoteField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcQrySecAgentACIDMapField *pQrySecAgentACIDMapField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcTraderOfferField *pTraderOfferField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcSyncStatusField *pSyncStatusField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcTransferFutureToBankReqField *pTransferFutureToBankReqField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcExchangeOrderInsertErrorField *pExchangeOrderInsertErrorField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcQryInstrumentField *pQryInstrumentField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcTransferQryDetailReqField *pTransferQryDetailReqField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcQryOptionInstrCommRateField *pQryOptionInstrCommRateField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcSyncingInvestorPositionField *pSyncingInvestorPositionField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcCFMMCTradingAccountKeyField *pCFMMCTradingAccountKeyField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcQryBrokerUserFunctionField *pQryBrokerUserFunctionField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcReqTransferField *pReqTransferField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcExchangeMarginRateAdjustField *pExchangeMarginRateAdjustField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcLinkManField *pLinkManField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcBrokerTradingParamsField *pBrokerTradingParamsField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcRspRepealField *pRspRepealField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcInstrumentMarginRateField *pInstrumentMarginRateField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcInvestorPositionDetailField *pInvestorPositionDetailField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcMarginModelField *pMarginModelField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcQryErrExecOrderField *pQryErrExecOrderField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcQryProductGroupField *pQryProductGroupField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcEWarrantOffsetField *pEWarrantOffsetField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcQryExchangeOrderField *pQryExchangeOrderField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcSyncFundMortgageField *pSyncFundMortgageField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcMarketDataBestPriceField *pMarketDataBestPriceField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcVerifyInvestorPasswordField *pVerifyInvestorPasswordField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcInputExecOrderField *pInputExecOrderField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcSpecificInstrumentField *pSpecificInstrumentField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcNotifySyncKeyField *pNotifySyncKeyField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcTransferBankField *pTransferBankField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcQryCombActionField *pQryCombActionField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcQryExchangeQuoteActionField *pQryExchangeQuoteActionField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcInvestorProductGroupMarginField *pInvestorProductGroupMarginField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcQryPartBrokerField *pQryPartBrokerField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcMarketDataAsk23Field *pMarketDataAsk23Field, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcQryLoginForbiddenUserField *pQryLoginForbiddenUserField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcBrokerUserOTPParamField *pBrokerUserOTPParamField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcQryTradingNoticeField *pQryTradingNoticeField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcExchangeQuoteField *pExchangeQuoteField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcQryLinkManField *pQryLinkManField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcQryTradeField *pQryTradeField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcRspUserLoginField *pRspUserLoginField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcQryInstrumentStatusField *pQryInstrumentStatusField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcRspTransferField *pRspTransferField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcBrokerUserEventField *pBrokerUserEventField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcContractBankField *pContractBankField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcSyncingInstrumentTradingRightField *pSyncingInstrumentTradingRightField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcReqOpenAccountField *pReqOpenAccountField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcDepositResultInformField *pDepositResultInformField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcExchangeOrderField *pExchangeOrderField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcFutureSignIOField *pFutureSignIOField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcTransferFutureToBankRspField *pTransferFutureToBankRspField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcQryInvestorProductGroupMarginField *pQryInvestorProductGroupMarginField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcExchangeOrderActionErrorField *pExchangeOrderActionErrorField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcNoticeField *pNoticeField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcCombActionField *pCombActionField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcInputBatchOrderActionField *pInputBatchOrderActionField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcTradingAccountPasswordUpdateField *pTradingAccountPasswordUpdateField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcQryExchangeOrderActionField *pQryExchangeOrderActionField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcOptionInstrCommRateField *pOptionInstrCommRateField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcQryProductExchRateField *pQryProductExchRateField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcQryCFMMCTradingAccountKeyField *pQryCFMMCTradingAccountKeyField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcInstrumentMarginRateAdjustField *pInstrumentMarginRateAdjustField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcQrySettlementInfoField *pQrySettlementInfoField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcInvestorGroupField *pInvestorGroupField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcOptionInstrMarginAdjustField *pOptionInstrMarginAdjustField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcExchangeExecOrderField *pExchangeExecOrderField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcVerifyCustInfoField *pVerifyCustInfoField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcBrokerTradingAlgosField *pBrokerTradingAlgosField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcInvestorField *pInvestorField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcSettlementInfoField *pSettlementInfoField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcMulticastGroupInfoField *pMulticastGroupInfoField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcMarketDataAveragePriceField *pMarketDataAveragePriceField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcQryExchangeForQuoteField *pQryExchangeForQuoteField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcQryInvestorPositionDetailField *pQryInvestorPositionDetailField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcQryParkedOrderField *pQryParkedOrderField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcQryBrokerField *pQryBrokerField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcSettlementInfoConfirmField *pSettlementInfoConfirmField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcRspFutureSignInField *pRspFutureSignInField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcMarketDataBid45Field *pMarketDataBid45Field, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcQryInvestorPositionCombineDetailField *pQryInvestorPositionCombineDetailField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcQryForQuoteField *pQryForQuoteField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcSyncingTradingAccountField *pSyncingTradingAccountField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcSyncingInstrumentMarginRateField *pSyncingInstrumentMarginRateField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcCommPhaseField *pCommPhaseField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcMarketDataLastMatchField *pMarketDataLastMatchField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcOrderField *pOrderField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcQryBrokerUserField *pQryBrokerUserField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcAuthenticationInfoField *pAuthenticationInfoField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcMarketDataExchangeField *pMarketDataExchangeField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcOptionInstrTradingRightField *pOptionInstrTradingRightField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcInstrumentField *pInstrumentField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcTradingAccountField *pTradingAccountField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcExchangeSequenceField *pExchangeSequenceField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcTradingAccountReserveField *pTradingAccountReserveField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcQryErrOrderField *pQryErrOrderField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcOptionInstrMiniMarginField *pOptionInstrMiniMarginField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcTradingCodeField *pTradingCodeField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcInvestorPositionCombineDetailField *pInvestorPositionCombineDetailField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcQryDepthMarketDataField *pQryDepthMarketDataField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcPartBrokerField *pPartBrokerField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcTradeField *pTradeField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcQueryMaxOrderVolumeField *pQueryMaxOrderVolumeField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcQryMDTraderOfferField *pQryMDTraderOfferField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcPositionProfitAlgorithmField *pPositionProfitAlgorithmField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcRspSyncKeyField *pRspSyncKeyField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcInputExecOrderActionField *pInputExecOrderActionField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcInstrumentCommissionRateField *pInstrumentCommissionRateField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcCancelAccountField *pCancelAccountField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcSyncingTradingCodeField *pSyncingTradingCodeField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcQryExchangeCombActionField *pQryExchangeCombActionField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcForQuoteField *pForQuoteField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcBatchOrderActionField *pBatchOrderActionField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcInstrumentTradingRightField *pInstrumentTradingRightField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcInputOrderActionField *pInputOrderActionField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcReqFutureSignOutField *pReqFutureSignOutField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcInputCombActionField *pInputCombActionField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcQryQuoteActionField *pQryQuoteActionField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcMarketDataBid23Field *pMarketDataBid23Field, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcInputOrderField *pInputOrderField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcInputQuoteField *pInputQuoteField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcExchangeForQuoteField *pExchangeForQuoteField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcReqQueryAccountField *pReqQueryAccountField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcRspFutureSignOutField *pRspFutureSignOutField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcQryTraderOfferField *pQryTraderOfferField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcQryTradingCodeField *pQryTradingCodeField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcChangeAccountField *pChangeAccountField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcQryExecOrderActionField *pQryExecOrderActionField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcExchangeMarginRateField *pExchangeMarginRateField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcBrokerSyncField *pBrokerSyncField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcQryInvestorGroupField *pQryInvestorGroupField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcBrokerUserField *pBrokerUserField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcQrySettlementInfoConfirmField *pQrySettlementInfoConfirmField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcQryForQuoteParamField *pQryForQuoteParamField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcQryUserSessionField *pQryUserSessionField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcBrokerDepositField *pBrokerDepositField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcQryInstrumentTradingRightField *pQryInstrumentTradingRightField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcQryBrokerTradingParamsField *pQryBrokerTradingParamsField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcQryTraderField *pQryTraderField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcUserLogoutField *pUserLogoutField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcTradingNoticeField *pTradingNoticeField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcBrokerWithdrawAlgorithmField *pBrokerWithdrawAlgorithmField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcRemoveParkedOrderActionField *pRemoveParkedOrderActionField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcAccountregisterField *pAccountregisterField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcMarketDataStaticField *pMarketDataStaticField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcExchangeOrderActionField *pExchangeOrderActionField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcNotifyQueryAccountField *pNotifyQueryAccountField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcQryExchangeMarginRateAdjustField *pQryExchangeMarginRateAdjustField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcErrOrderField *pErrOrderField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcQryTransferBankField *pQryTransferBankField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcQryTransferSerialField *pQryTransferSerialField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcOpenAccountField *pOpenAccountField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcQryInstrumentMarginRateField *pQryInstrumentMarginRateField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcInvestorPositionField *pInvestorPositionField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcQrySyncFundMortgageField *pQrySyncFundMortgageField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcTransferSerialField *pTransferSerialField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcSyncingInvestorField *pSyncingInvestorField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcRspInfoField *pRspInfoField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcVerifyFuturePasswordAndCustInfoField *pVerifyFuturePasswordAndCustInfoField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcInvestorAccountField *pInvestorAccountField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcQryInstrumentCommissionRateField *pQryInstrumentCommissionRateField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcRspQueryTradeResultBySerialField *pRspQueryTradeResultBySerialField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcStrikeOffsetField *pStrikeOffsetField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcErrExecOrderActionField *pErrExecOrderActionField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcQryExchangeExecOrderField *pQryExchangeExecOrderField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcQryEWarrantOffsetField *pQryEWarrantOffsetField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcReqSyncKeyField *pReqSyncKeyField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcQueryMaxOrderVolumeWithPriceField *pQueryMaxOrderVolumeWithPriceField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcLoadSettlementInfoField *pLoadSettlementInfoField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcProductGroupField *pProductGroupField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcErrExecOrderField *pErrExecOrderField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcQrySuperUserFunctionField *pQrySuperUserFunctionField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcQuoteActionField *pQuoteActionField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcParkedOrderActionField *pParkedOrderActionField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcQryCommRateModelField *pQryCommRateModelField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcVerifyFuturePasswordField *pVerifyFuturePasswordField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcQryNoticeField *pQryNoticeField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcQryExchangeMarginRateField *pQryExchangeMarginRateField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcTradingAccountPasswordUpdateV1Field *pTradingAccountPasswordUpdateV1Field, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcExecOrderField *pExecOrderField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcTransferQryBankRspField *pTransferQryBankRspField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcParkedOrderField *pParkedOrderField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcQryOrderField *pQryOrderField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcOrderActionField *pOrderActionField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcExchangeRateField *pExchangeRateField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcBrokerUserFunctionField *pBrokerUserFunctionField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcErrOrderActionField *pErrOrderActionField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcBrokerUserPasswordField *pBrokerUserPasswordField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcReqChangeAccountField *pReqChangeAccountField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcReqCancelAccountField *pReqCancelAccountField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcQryContractBankField *pQryContractBankField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcCFMMCBrokerKeyField *pCFMMCBrokerKeyField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcExchangeQuoteActionField *pExchangeQuoteActionField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcProductField *pProductField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcQryExchangeExecOrderActionField *pQryExchangeExecOrderActionField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcReqUserLoginField *pReqUserLoginField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcRspAuthenticateField *pRspAuthenticateField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcForceUserLogoutField *pForceUserLogoutField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcQryBatchOrderActionField *pQryBatchOrderActionField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcUserRightsAssignField *pUserRightsAssignField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcLoginInfoField *pLoginInfoField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcReqAuthenticateField *pReqAuthenticateField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcQrySuperUserField *pQrySuperUserField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcCFMMCTradingAccountTokenField *pCFMMCTradingAccountTokenField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcDisseminationField *pDisseminationField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcForQuoteRspField *pForQuoteRspField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcFensUserInfoField *pFensUserInfoField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcUserIPField *pUserIPField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcUserPasswordUpdateField *pUserPasswordUpdateField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcQuoteField *pQuoteField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcQryParkedOrderActionField *pQryParkedOrderActionField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcReqRepealField *pReqRepealField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcQryStrikeOffsetField *pQryStrikeOffsetField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcOptionInstrTradeCostField *pOptionInstrTradeCostField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcSettlementRefField *pSettlementRefField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcReqQueryTradeResultBySerialField *pReqQueryTradeResultBySerialField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcTraderField *pTraderField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcProductExchRateField *pProductExchRateField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcExchangeBatchOrderActionField *pExchangeBatchOrderActionField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcExecOrderActionField *pExecOrderActionField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcQryHisOrderField *pQryHisOrderField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcLoginForbiddenUserField *pLoginForbiddenUserField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcDepthMarketDataField *pDepthMarketDataField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcTransferBankToFutureRspField *pTransferBankToFutureRspField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcCombInstrumentGuardField *pCombInstrumentGuardField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcInputForQuoteField *pInputForQuoteField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcTradingAccountPasswordField *pTradingAccountPasswordField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcReturnResultField *pReturnResultField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcMDTraderOfferField *pMDTraderOfferField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcExchangeTradeField *pExchangeTradeField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcQryOptionInstrTradingRightField *pQryOptionInstrTradingRightField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcQryFrontStatusField *pQryFrontStatusField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcCommRateModelField *pCommRateModelField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcQryBrokerTradingAlgosField *pQryBrokerTradingAlgosField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcIndexPriceField *pIndexPriceField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcQryMarginModelField *pQryMarginModelField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcExchangeCombActionField *pExchangeCombActionField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcSuperUserField *pSuperUserField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcQryExchangeRateField *pQryExchangeRateField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcQryCombinationLegField *pQryCombinationLegField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcQrySyncStatusField *pQrySyncStatusField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcTransferQryBankReqField *pTransferQryBankReqField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcFrontStatusField *pFrontStatusField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcQryExchangeQuoteField *pQryExchangeQuoteField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcInvestorWithdrawAlgorithmField *pInvestorWithdrawAlgorithmField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcSyncingInstrumentCommissionRateField *pSyncingInstrumentCommissionRateField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcQryErrExecOrderActionField *pQryErrExecOrderActionField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcQryOrderActionField *pQryOrderActionField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcForQuoteParamField *pForQuoteParamField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcCurrentTimeField *pCurrentTimeField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcLogoutAllField *pLogoutAllField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcDiscountField *pDiscountField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcQryProductField *pQryProductField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcQryTradingAccountField *pQryTradingAccountField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcSyncDepositField *pSyncDepositField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcReqDayEndFileReadyField *pReqDayEndFileReadyField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcMarketDataUpdateTimeField *pMarketDataUpdateTimeField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcQryInvestorField *pQryInvestorField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcCombinationLegField *pCombinationLegField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcQryCombInstrumentGuardField *pQryCombInstrumentGuardField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcQryExecOrderField *pQryExecOrderField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcQrySyncDepositField *pQrySyncDepositField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcSyncingInvestorGroupField *pSyncingInvestorGroupField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcNotifyFutureSignOutField *pNotifyFutureSignOutField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcSecAgentACIDMapField *pSecAgentACIDMapField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcBrokerField *pBrokerField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcQueryBrokerDepositField *pQueryBrokerDepositField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcQryOptionInstrTradeCostField *pQryOptionInstrTradeCostField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcMarketDataField *pMarketDataField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcMarketDataAsk45Field *pMarketDataAsk45Field, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcNotifyFutureSignInField *pNotifyFutureSignInField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcOptionInstrDeltaField *pOptionInstrDeltaField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcExchangeField *pExchangeField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcRemoveParkedOrderField *pRemoveParkedOrderField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcRspQueryAccountField *pRspQueryAccountField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcExchangeExecOrderActionField *pExchangeExecOrderActionField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcTradingNoticeInfoField *pTradingNoticeInfoField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcQryAccountregisterField *pQryAccountregisterField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcMarketDataBaseField *pMarketDataBaseField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcUserSessionField *pUserSessionField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcInputQuoteActionField *pInputQuoteActionField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcQryExchangeSequenceField *pQryExchangeSequenceField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcQryBrokerUserEventField *pQryBrokerUserEventField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcQryExchangeField *pQryExchangeField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcManualSyncBrokerUserOTPField *pManualSyncBrokerUserOTPField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcBrokerUserRightAssignField *pBrokerUserRightAssignField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcInstrumentStatusField *pInstrumentStatusField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcTransferHeaderField *pTransferHeaderField, PyObject *dict);
int PyCTP_Struct_FromPyDict(CThostFtdcSuperUserFunctionField *pSuperUserFunctionField, PyObject *dict);

#endif